import { chromium } from 'playwright';
import { execSync } from 'child_process';
const NIX_LIB_PATHS = execSync("nix-build --no-out-link '<nixpkgs>' -A mesa -A libgbm -A nss -A nspr -A atk -A at-spi2-atk -A at-spi2-core -A cups -A dbus -A libdrm -A libxkbcommon -A alsa-lib -A pango -A cairo -A expat -A xorg.libX11 -A xorg.libXcomposite -A xorg.libXdamage -A xorg.libXext -A xorg.libXfixes -A xorg.libXrandr -A xorg.libxcb -A xorg.libxshmfence 2>/dev/null", { encoding:'utf8'}).trim().split('\n').map(p=>p+'/lib').join(':');
process.env.LD_LIBRARY_PATH = [process.env.LD_LIBRARY_PATH, NIX_LIB_PATHS].filter(Boolean).join(':');
const seed = Date.now();
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.goto('https://dev.traydbook.com/signup',{waitUntil:'domcontentloaded'});
await page.click('button:has-text("Contractor")'); await page.click('button:text-is("Continue")');
await page.waitForURL('**/trade-select',{timeout:8000}).catch(()=>{});
await page.click('button:has-text("Electrician")'); await page.click('button:has-text("Continue as")');
await page.waitForURL('**/contractor',{timeout:8000}).catch(()=>{});
await page.locator('input[type="email"]').fill(`trumpoly2025+p${seed}@gmail.com`);
await page.locator('input[type="password"]').nth(0).fill(`Trayd-${seed}-Aa1!`);
await page.locator('input[type="password"]').nth(1).fill(`Trayd-${seed}-Aa1!`);
await page.click('button[type="submit"]');
await page.waitForLoadState('networkidle',{timeout:8000}).catch(()=>{});
await page.waitForTimeout(2000);
console.log('AFTER SIGNUP:', page.url());
await page.click('button:has-text("Contractor")');
await page.waitForTimeout(800);
await page.click('button:text-is("Continue")');
await page.waitForLoadState('networkidle',{timeout:8000}).catch(()=>{});
await page.waitForTimeout(2500);
console.log('\nAFTER /onboarding Continue:', page.url());
console.log('--- body ---\n' + (await page.locator('body').innerText()).slice(0,2200));
const fields = await page.evaluate(() => [...document.querySelectorAll('input, textarea, select, button')].filter(el=>el.offsetParent).map(el=>({
  tag:el.tagName,type:el.type||'',name:el.name||'',id:el.id||'',placeholder:el.placeholder||'',text:(el.textContent||'').trim().slice(0,60),
})));
console.log('\n--- fields ---\n' + JSON.stringify(fields,null,2));
await browser.close();
