import { chromium } from 'playwright';
import { execSync } from 'child_process';
const NIX_LIB_PATHS = execSync("nix-build --no-out-link '<nixpkgs>' -A mesa -A libgbm -A nss -A nspr -A atk -A at-spi2-atk -A at-spi2-core -A cups -A dbus -A libdrm -A libxkbcommon -A alsa-lib -A pango -A cairo -A expat -A xorg.libX11 -A xorg.libXcomposite -A xorg.libXdamage -A xorg.libXext -A xorg.libXfixes -A xorg.libXrandr -A xorg.libxcb -A xorg.libxshmfence 2>/dev/null", { encoding:'utf8'}).trim().split('\n').map(p=>p+'/lib').join(':');
process.env.LD_LIBRARY_PATH = [process.env.LD_LIBRARY_PATH, NIX_LIB_PATHS].filter(Boolean).join(':');
const seed = Date.now();
const email = `trumpoly2025+verify7${seed}@gmail.com`;
console.log('PROBE EMAIL:', email);
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const calls = [];
page.on('response', r => { const u=r.url(); if(u.includes('traydbook')||u.includes('supabase')) calls.push(`${r.status()} ${r.request().method()} ${u.slice(0,140)}`); });
await page.goto('https://dev.traydbook.com/signup',{waitUntil:'domcontentloaded'});
await page.click('button:has-text("Contractor")'); await page.click('button:text-is("Continue")');
await page.waitForURL('**/trade-select',{timeout:8000}).catch(()=>{});
await page.click('button:has-text("Electrician")'); await page.click('button:has-text("Continue as")');
await page.waitForURL('**/contractor',{timeout:8000}).catch(()=>{});
await page.locator('input[type="email"]').fill(email);
await page.locator('input[type="password"]').nth(0).fill(`Trayd-${seed}-Aa1!`);
await page.locator('input[type="password"]').nth(1).fill(`Trayd-${seed}-Aa1!`);
await page.click('button[type="submit"]');
await page.waitForURL('**/onboarding',{timeout:10000}).catch(()=>{});
await page.waitForTimeout(1500);
await page.click('button:has-text("Contractor")'); await page.waitForTimeout(400);
await page.click('button:text-is("Continue")');
await page.waitForTimeout(2000);
await page.selectOption('select >> nth=1', 'CA');
await page.locator('input[placeholder*="Full name" i]').fill(`Verify ${seed}`);
await page.click('button:has-text("Finish Setup")');
await page.waitForURL('**/wallet-setup',{timeout:10000}).catch(()=>{});
await page.waitForTimeout(2000);
console.log('on wallet:', page.url());

await page.click('label:has(input[type="checkbox"])');
await page.waitForTimeout(800);
calls.length = 0;
console.log('\n>>> clicking Confirm & Go to Feed');
await page.click('button:has-text("Confirm & Go to Feed")');
await page.waitForTimeout(6000);
console.log('FINAL URL:', page.url());
console.log('\n--- HTTP calls during/after confirm ---');
calls.forEach(c => console.log(' ', c));
console.log('\n--- body sample ---');
console.log((await page.locator('body').innerText()).slice(0,800));
await browser.close();
