kind = "web"
previewPath = "/"
title = "Cooperanth-sim-runner"
version = "1.0.0"
id = "artifacts/cooperanth-sim-runner"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19179

[services.development]
run = "pnpm --filter @workspace/cooperanth-sim-runner run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/cooperanth-sim-runner", "run", "build" ]
publicDir = "artifacts/cooperanth-sim-runner/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19179"
BASE_PATH = "/"
